version: "3"
services:
  app:
    build: .
    container_name: airframe
    image: airbloc/airframe
    ports:
      - "8080:8080"
      - "9090:9090"
    command:
      - "airframe"
      - "-d"
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
