version: 2
jobs:
  unit-test:
    docker:
      - image: circleci/golang:1.11
    environment:
      TEST_RESULTS: "/tmp/test-results"
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
            - go-mod-v1-
      - run:
          name: Setup test tools
          command: |
            cp go.sum go.sum.original
            mkdir -p $TEST_RESULTS/gotest
      - run:
          name: Run unit tests
          command: |
            echo 'export GO111MODULE=on' >> $BASH_ENV
            GOTEST="gotestsum --junitfile ${TEST_RESULTS}/gotest/results.xml --" make test
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum.original" }}
          paths:
            - "/go/pkg/mod"
      - store_test_results:
          path: /tmp/test-results

  e2e-test:
    docker:
      - image: circleci/golang:1.11
    environment:
      TEST_RESULTS: "/tmp/test-results"
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Setup test tools
          command: |
            mkdir -p $TEST_RESULTS/e2etest
      - run:
          name: Build Image
          command: docker build -t airbloc/airframe .
      - run:
          name: End-to-End Test Container
          command: |
            docker-compose -f docker-compose.yml -f test/e2e/docker-compose.e2e.yml run start_app
            docker-compose -f docker-compose.yml -f test/e2e/docker-compose.e2e.yml run e2e-tests

workflows:
  version: 2
  test:
    jobs:
      - unit-test
      - e2e-test
