// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/api.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	CreatedAt            uint64   `protobuf:"varint,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	LastUpdatedAt        uint64   `protobuf:"varint,4,opt,name=lastUpdatedAt,proto3" json:"lastUpdatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{0}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetResponse) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *GetResponse) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *GetResponse) GetLastUpdatedAt() uint64 {
	if m != nil {
		return m.LastUpdatedAt
	}
	return 0
}

type PutRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Signature            []byte   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{1}
}

func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (m *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(m, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

func (m *PutRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PutRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PutRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *PutRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type PutResponse struct {
	Uri                  string   `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	FeeUsed              uint64   `protobuf:"varint,2,opt,name=feeUsed,proto3" json:"feeUsed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}
func (*PutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{2}
}

func (m *PutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResponse.Unmarshal(m, b)
}
func (m *PutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResponse.Marshal(b, m, deterministic)
}
func (m *PutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResponse.Merge(m, src)
}
func (m *PutResponse) XXX_Size() int {
	return xxx_messageInfo_PutResponse.Size(m)
}
func (m *PutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutResponse proto.InternalMessageInfo

func (m *PutResponse) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *PutResponse) GetFeeUsed() uint64 {
	if m != nil {
		return m.FeeUsed
	}
	return 0
}

func init() {
	proto.RegisterType((*GetResponse)(nil), "GetResponse")
	proto.RegisterType((*PutRequest)(nil), "PutRequest")
	proto.RegisterType((*PutResponse)(nil), "PutResponse")
}

func init() { proto.RegisterFile("proto/api.proto", fileDescriptor_ecf0878b123623e2) }

var fileDescriptor_ecf0878b123623e2 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xbf, 0x4b, 0xc5, 0x30,
	0x14, 0x85, 0x69, 0x1b, 0x95, 0xde, 0xf7, 0xfc, 0x41, 0x70, 0xe8, 0xf0, 0x86, 0x52, 0x1c, 0x3a,
	0xe9, 0xe0, 0xe4, 0xa8, 0x8b, 0xab, 0x5c, 0x78, 0x8b, 0x5b, 0x6a, 0xae, 0x12, 0x90, 0x26, 0x26,
	0x37, 0x88, 0xf8, 0xcf, 0xcb, 0xbb, 0x8d, 0x16, 0xb7, 0xef, 0x1e, 0x0e, 0x7c, 0x27, 0x81, 0xf3,
	0x10, 0x3d, 0xfb, 0x1b, 0x13, 0xdc, 0xb5, 0xd0, 0xf0, 0x0d, 0x9b, 0x47, 0x62, 0xa4, 0x14, 0xfc,
	0x9c, 0x48, 0x6b, 0x50, 0xd6, 0xb0, 0xe9, 0xaa, 0xbe, 0x1a, 0xb7, 0x28, 0xac, 0x2f, 0xe1, 0xc8,
	0x7f, 0xce, 0x14, 0xbb, 0xba, 0xaf, 0xc6, 0x16, 0x97, 0x43, 0xef, 0xa0, 0x7d, 0x89, 0x64, 0x98,
	0xec, 0x3d, 0x77, 0x4d, 0x5f, 0x8d, 0x0a, 0xd7, 0x40, 0x5f, 0xc1, 0xe9, 0xbb, 0x49, 0xbc, 0x0f,
	0xb6, 0x34, 0x94, 0x34, 0xfe, 0x87, 0xc3, 0x04, 0xf0, 0x94, 0x19, 0xe9, 0x23, 0x53, 0xe2, 0x83,
	0x9b, 0xbf, 0x02, 0x89, 0xbb, 0x45, 0x61, 0x7d, 0x06, 0xb5, 0xb3, 0x45, 0x5c, 0x3b, 0xfb, 0xb7,
	0xaf, 0x59, 0x3a, 0xb2, 0x6f, 0x07, 0x6d, 0x72, 0x6f, 0xb3, 0xe1, 0x1c, 0x49, 0x3c, 0x5b, 0x5c,
	0x83, 0xe1, 0x0e, 0x36, 0xe2, 0x28, 0x0f, 0xbc, 0x80, 0x26, 0x47, 0x57, 0x1c, 0x07, 0xd4, 0x1d,
	0x9c, 0xbc, 0x12, 0xed, 0x13, 0x2d, 0x1e, 0x85, 0xbf, 0xe7, 0x83, 0x7a, 0xae, 0xc3, 0x34, 0x1d,
	0xcb, 0x47, 0xdd, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x56, 0xa2, 0x33, 0x0c, 0x3b, 0x01, 0x00,
	0x00,
}
