// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpcserver/api.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb4e1df46406b2cd, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetResponse struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	CreatedAt            uint64   `protobuf:"varint,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	LastUpdatedAt        uint64   `protobuf:"varint,4,opt,name=lastUpdatedAt,proto3" json:"lastUpdatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb4e1df46406b2cd, []int{1}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *GetResponse) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *GetResponse) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *GetResponse) GetLastUpdatedAt() uint64 {
	if m != nil {
		return m.LastUpdatedAt
	}
	return 0
}

type QueryRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Query                string   `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Skip                 uint64   `protobuf:"varint,3,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit                uint64   `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb4e1df46406b2cd, []int{2}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *QueryRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *QueryRequest) GetSkip() uint64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *QueryRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type QueryResponse struct {
	Results              []*GetResponse `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb4e1df46406b2cd, []int{3}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetResults() []*GetResponse {
	if m != nil {
		return m.Results
	}
	return nil
}

type PutRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Signature            []byte   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb4e1df46406b2cd, []int{4}
}

func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (m *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(m, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

func (m *PutRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PutRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PutRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *PutRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type PutResponse struct {
	Created              bool     `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	FeeUsed              uint64   `protobuf:"varint,2,opt,name=feeUsed,proto3" json:"feeUsed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}
func (*PutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb4e1df46406b2cd, []int{5}
}

func (m *PutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResponse.Unmarshal(m, b)
}
func (m *PutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResponse.Marshal(b, m, deterministic)
}
func (m *PutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResponse.Merge(m, src)
}
func (m *PutResponse) XXX_Size() int {
	return xxx_messageInfo_PutResponse.Size(m)
}
func (m *PutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutResponse proto.InternalMessageInfo

func (m *PutResponse) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *PutResponse) GetFeeUsed() uint64 {
	if m != nil {
		return m.FeeUsed
	}
	return 0
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "GetRequest")
	proto.RegisterType((*GetResponse)(nil), "GetResponse")
	proto.RegisterType((*QueryRequest)(nil), "QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "QueryResponse")
	proto.RegisterType((*PutRequest)(nil), "PutRequest")
	proto.RegisterType((*PutResponse)(nil), "PutResponse")
}

func init() { proto.RegisterFile("rpcserver/api.proto", fileDescriptor_eb4e1df46406b2cd) }

var fileDescriptor_eb4e1df46406b2cd = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x6d, 0x9a, 0x94, 0x92, 0x4b, 0xda, 0xc1, 0x74, 0x88, 0xaa, 0x0e, 0x95, 0x85, 0x50, 0xa6,
	0x80, 0xca, 0xc0, 0x5c, 0x96, 0x8a, 0x89, 0x12, 0xa9, 0x0b, 0x5b, 0xd2, 0x1c, 0xc8, 0x50, 0x1a,
	0xd7, 0x76, 0x40, 0x15, 0x5f, 0xc0, 0x5f, 0x23, 0xbb, 0x4e, 0x93, 0x2e, 0x48, 0x6c, 0xf7, 0xce,
	0xef, 0xfc, 0x9e, 0x9f, 0x0f, 0x2e, 0x04, 0x5f, 0x4b, 0x14, 0x9f, 0x28, 0xae, 0x33, 0xce, 0x12,
	0x2e, 0x4a, 0x55, 0xd2, 0x1b, 0x80, 0x05, 0xaa, 0x14, 0x77, 0x15, 0x4a, 0x45, 0x08, 0x78, 0x6a,
	0xcf, 0x31, 0x72, 0xa6, 0x4e, 0xec, 0xa7, 0xa6, 0x26, 0x43, 0xe8, 0xb2, 0x22, 0xea, 0x9a, 0x4e,
	0x97, 0x15, 0xf4, 0x1b, 0x02, 0x33, 0x21, 0x79, 0xb9, 0x95, 0xa8, 0x47, 0x8a, 0x4c, 0x65, 0xf5,
	0x88, 0xae, 0xc9, 0x08, 0x7a, 0xe5, 0xd7, 0x16, 0x85, 0x9d, 0x3a, 0x00, 0x32, 0x01, 0x7f, 0x2d,
	0x30, 0x53, 0x58, 0xcc, 0x55, 0xe4, 0x4e, 0x9d, 0xd8, 0x4b, 0x9b, 0x06, 0xb9, 0x84, 0xc1, 0x26,
	0x93, 0x6a, 0xc5, 0x0b, 0xcb, 0xf0, 0x0c, 0xe3, 0xb4, 0x49, 0x73, 0x08, 0x9f, 0x2a, 0x14, 0xfb,
	0xbf, 0x0c, 0x8f, 0xa0, 0xb7, 0xd3, 0x9c, 0x5a, 0xdd, 0x00, 0xcd, 0x94, 0xef, 0x8c, 0x5b, 0x61,
	0x53, 0x6b, 0xe6, 0x86, 0x7d, 0xb0, 0x5a, 0xeb, 0x00, 0xe8, 0x1d, 0x0c, 0xac, 0x86, 0x7d, 0xe2,
	0x15, 0xf4, 0x05, 0xca, 0x6a, 0xa3, 0x64, 0xe4, 0x4c, 0xdd, 0x38, 0x98, 0x85, 0x49, 0x2b, 0x81,
	0xb4, 0x3e, 0xa4, 0x39, 0xc0, 0xb2, 0xfa, 0x4f, 0x96, 0xc7, 0xf0, 0xdc, 0x56, 0x78, 0x13, 0xf0,
	0x25, 0x7b, 0xdd, 0x66, 0xaa, 0x12, 0x68, 0x8c, 0x85, 0x69, 0xd3, 0xa0, 0x73, 0x08, 0x8c, 0x86,
	0xb5, 0x16, 0x41, 0xdf, 0x46, 0x68, 0x74, 0xce, 0xd3, 0x1a, 0xea, 0x93, 0x17, 0xc4, 0x95, 0xc4,
	0x83, 0x9e, 0x97, 0xd6, 0x70, 0xf6, 0xe3, 0x80, 0x3b, 0x5f, 0x3e, 0x90, 0x18, 0xfc, 0x05, 0xaa,
	0xc7, 0xfc, 0x0d, 0xd7, 0x8a, 0x04, 0x49, 0xb3, 0x06, 0xe3, 0x93, 0xf7, 0xd1, 0x0e, 0x49, 0x20,
	0x30, 0x89, 0x58, 0xee, 0x20, 0x69, 0xff, 0xc1, 0x78, 0x98, 0x9c, 0xc4, 0x45, 0x3b, 0xfa, 0xe6,
	0x65, 0xd5, 0xdc, 0xdc, 0x84, 0x32, 0x0e, 0x93, 0x96, 0x7b, 0xda, 0xb9, 0x0f, 0x9e, 0xfd, 0xe3,
	0x56, 0xe6, 0x67, 0x66, 0x25, 0x6f, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xd6, 0xbd, 0x78, 0xb4,
	0xa9, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	GetObject(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	QueryObject(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	PutObject(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) GetObject(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/API/GetObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) QueryObject(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, "/API/QueryObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) PutObject(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, "/API/PutObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	GetObject(context.Context, *GetRequest) (*GetResponse, error)
	QueryObject(context.Context, *QueryRequest) (*QueryResponse, error)
	PutObject(context.Context, *PutRequest) (*PutResponse, error)
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_GetObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/API/GetObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetObject(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_QueryObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).QueryObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/API/QueryObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).QueryObject(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_PutObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).PutObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/API/PutObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).PutObject(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetObject",
			Handler:    _API_GetObject_Handler,
		},
		{
			MethodName: "QueryObject",
			Handler:    _API_QueryObject_Handler,
		},
		{
			MethodName: "PutObject",
			Handler:    _API_PutObject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcserver/api.proto",
}
