# NOTE THAT this file should be executed on project root.
FROM golang:1.11-alpine as base

# Install build toolchain for alpine
RUN apk add --no-cache make git g++ musl-dev linux-headers bash ca-certificates
WORKDIR /airframe

# use go modules
ENV GO111MODULE=on

# 1. Fetch and cache go module dependencies
COPY go.mod .
COPY go.sum .
RUN go mod download

# 2. Copy rest
FROM base AS builder
COPY . .

CMD ["make", "test-e2e"]
